
name: development

services:
  auth-dev:
    user: root
    build: .
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      # Монтируем код для мгновенного hot-reload
      - ./src:/app/src:rw
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./poetry.lock:/app/poetry.lock:ro
    ports:
      - "8000:8000"
    depends_on:
      auth-postgres-dev:
        condition: service_healthy
      auth-redis-dev:
        condition: service_started
    secrets:
      - jwt_private_key
      - jwt_public_key
    networks:
      - auth-network
      - app-network
    # Переопределяем CMD для включения reload
    command: sh -c "
        alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir src
        "
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"   # Порт RabbitMQ для обмена сообщениями
      - "15672:15672" # Веб-менеджер RabbitMQ для мониторинга
    networks:
      - app-network
  auth-postgres-dev:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # другой порт, чтобы не конфликтовать с локальной БД
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-redis-dev:
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server
      --appendonly yes
      --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data_dev:/data
    ports:
      - "6380:6379"
    networks:
      - auth-network

  # === Удобные GUI-инструменты ===
  auth-adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    environment:
      ADMINER_DEFAULT_SERVER: auth-postgres-dev
    depends_on:
      - auth-postgres-dev
    networks:
      - auth-network

  auth-pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "5050:80"
    env_file:
      - .env.dev
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - auth-postgres-dev
    networks:
      - auth-network

volumes:
  postgres_data_dev:
  redis_data_dev:
  pgadmin_data:

networks:
  auth-network:
    driver: bridge
  app-network:
    driver: bridge

secrets:
  jwt_private_key:
    file: ./keys/private_key.pem
  jwt_public_key:
    file: ./keys/public_key.pem
